# Setup
title:               5E УКРАЇНСЬКОЮ
tagline:             'Довідник з правил 5e'
description:         'Переклад <a href="https://media.wizards.com/2016/downloads/DND/SRD-OGL_V5.1.pdf">Source Reference Document</a> на основі <a href="https://en.wikipedia.org/wiki/Open_Game_License" target="_blank">Open Game License v.1.0a</a>.'
url:                 ''
baseurl:             'jekyll_canyon_theme'
host:                0.0.0.0
#paginate:            5
#permalink:           pretty
timezone:             Europe/Kiev

# About/contact
author:
  name:              Robort Bender
  url:               https://benderrodrigez.com
  email:             robort.bender@gmail.com

# Gems
#plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y

# Collections
collections_dir: 5esrd
collections:
  docs:
    output: true
  items:
    output: true
  monsters:
    output: true
  spells:
    output: true

# Social links
twitter_username: boo
github_username:  boo
stackoverflow_username: 
dribbble_username: 
facebook_username: boo
flickr_username: 
instagram_username: boo
linkedin_username: boo
xing_username: 
pinterest_username: 
youtube_username: boo
orcid_username: 
googlescholar_username: 
