# Setup
title:               5e українською
tagline:             'Довідник з правил 5e'
description:         'Переклад <a href="https://media.wizards.com/2016/downloads/DND/SRD-OGL_V5.1.pdf">Source Reference Document</a> на основі <a href="https://en.wikipedia.org/wiki/Open_Game_License" target="_blank">Open Game License v.1.0a</a>.'
url:                 ''
baseurl:             '/jekyll_canyon_theme'
host:                0.0.0.0
#paginate:            5
#permalink:           pretty

# About/contact
author:
  name:              Robort Bender
  url:               https://benderrodrigez.com
  email:             robort.bender@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y

# Collections
collections:
  docs:
    output: true
  test:
    output: true
